---
stages:
  - lint
  - deployment test

before_script:
  - rm -rf molecule/resources/provisioning
  - ansible --version
  - ansible-lint --version
  - molecule --version
  - git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning

variables:
  GET_SOURCES_ATTEMPTS: "5"

Lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - yamllint . -c .yamllint
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - aws

.Docker zookeeper:
  stage: deployment test
  script:
    - molecule test -s default
  tags:
    - aws

AWS zookeeper:
  image:
    name: leandelivery/docker-ansible-ci:ansible-2.8
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct
  tags:
    - aws

AZURE zookeeper:
  stage: deployment test
  script:
    - molecule test -s cloud-azure-direct
  tags:
    - azure

.AWS Windows zookeeper:
  image:
    name: leandelivery/docker-ansible-ci:ansible-2.7
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-windows
  tags:
    - aws

.EPC zookeeper:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-delegated
  tags:
    - delegated
