---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:

  - name: test-aws-Windows2016-zookeeper
    aws_image_id: ami-00a20f508263efd30
    platform: windows2016core
    aws_region: us-east-1
    instance_type: m5.large
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.14
    aws_sec_group:
      - default
    wait_timeout: 1800
    groups:
      - windows

  - name: test-aws-Windows2019-zookeeper
    aws_image_id: ami-0477b9335a5a75438
    platform: windows2019core
    aws_region: us-east-1
    instance_type: m5.large
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.14
    aws_sec_group:
      - default
    wait_timeout: 1800
    groups:
      - windows
provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  connection_options:
    ansible_connection: winrm
  inventory:
    group_vars:
      windows:
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', true) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
  playbooks:
    create: ../resources/provisioning/WINRM/create.yml
    destroy: ../resources/provisioning/WINRM/destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-windows
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
