---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-zookeeper
    image: ami-9887c6e7
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: False
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - zookeeper
      - zookeeper_centos

  # - name: test-aws-centos6-zookeeper
  #   image: ami-1585c46a
  #   instance_type: m4.large
  #   region: us-east-1
  #   vpc_subnet_id: subnet-05a2ef2b767afec50
  #   assign_public_ip: False
  #   spot_price: 0.04
  #   security_group_name:
  #     - default
  #   wait_timeout: 1800
  #   ssh_user: centos
  #   groups:
  #     - rhel_family
  #     - zookeeper
  #     - zookeeper_centos

  - name: test-aws-ubuntu16-zookeeper
    image: ami-0f9cf087c1f27d9b1
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: False
    security_group_name:
      - default
    spot_price: 0.04
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - zookeeper
      - zookeeper_ubuntu

  - name: test-aws-ubuntu18-zookeeper
    image: ami-0ac019f4fcb7cb7e6
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: False
    security_group_name:
      - default
    spot_price: 0.04
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - zookeeper
      - zookeeper_ubuntu

provisioner:
  name: ansible
  log: False
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../resources/provisioning/AWS/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
  lint:
    name: ansible-lint
  env:
    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY}
scenario:
  name: cloud-aws-direct
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
